[package]
name = "gaia_access"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.0", default-features = false, features = ["blocking", "rustls-tls"] } # Downloading files
strum = { version = "0.26.0", no-default-features = true, features = ["derive"] } # Derive string from enum
serde = { version = "1.0", default-features = false, features = ["derive"] } # (De)Serialization
serde_json = { version = "1.0", default-features = false, features = ["std"] }
strum_macros = "0.26.0" # Derive string from enum

[dev-dependencies]
xmltree = "0.10.0" # XML DeSerialization

[features]
public_hubble_sc = []
public_hipparcos = []
public_hipparcos_newreduction = []
public_igsl_source = []
public_tycho2 = []
public_igsl_source_catalog_ids = []
public_dual = []
public = ["public_hubble_sc", "public_hipparcos", "public_hipparcos_newreduction", "public_igsl_source", "public_tycho2", "public_igsl_source_catalog_ids", "public_dual"]
gaiadr1_gsc23_neighbourhood = []
gaiadr1_ucac4_best_neighbour = []
gaiadr1_ppmxl_neighbourhood = []
gaiadr1_ppmxl_original_valid = []
gaiadr1_tmass_neighbourhood = []
gaiadr1_gaia_source = []
gaiadr1_phot_variable_time_series_gfov = []
gaiadr1_allwise_best_neighbour = []
gaiadr1_urat1_original_valid = []
gaiadr1_aux_qso_icrf2_match = []
gaiadr1_sdss_dr9_best_neighbour = []
gaiadr1_sdss_dr9_neighbourhood = []
gaiadr1_gsc23_original_valid = []
gaiadr1_allwise_original_valid = []
gaiadr1_rrlyrae = []
gaiadr1_ucac4_neighbourhood = []
gaiadr1_tmass_original_valid = []
gaiadr1_gsc23_best_neighbour = []
gaiadr1_ext_phot_zero_point = []
gaiadr1_cepheid = []
gaiadr1_urat1_neighbourhood = []
gaiadr1_urat1_best_neighbour = []
gaiadr1_allwise_neighbourhood = []
gaiadr1_variable_summary = []
gaiadr1_tgas_source = []
gaiadr1_tmass_best_neighbour = []
gaiadr1_ucac4_original_valid = []
gaiadr1_ppmxl_best_neighbour = []
gaiadr1_phot_variable_time_series_gfov_statistical_parameters = []
gaiadr1_sdssdr9_original_valid = []
gaiadr1 = ["gaiadr1_gsc23_neighbourhood", "gaiadr1_ucac4_best_neighbour", "gaiadr1_ppmxl_neighbourhood", "gaiadr1_ppmxl_original_valid", "gaiadr1_tmass_neighbourhood", "gaiadr1_gaia_source", "gaiadr1_phot_variable_time_series_gfov", "gaiadr1_allwise_best_neighbour", "gaiadr1_urat1_original_valid", "gaiadr1_aux_qso_icrf2_match", "gaiadr1_sdss_dr9_best_neighbour", "gaiadr1_sdss_dr9_neighbourhood", "gaiadr1_gsc23_original_valid", "gaiadr1_allwise_original_valid", "gaiadr1_rrlyrae", "gaiadr1_ucac4_neighbourhood", "gaiadr1_tmass_original_valid", "gaiadr1_gsc23_best_neighbour", "gaiadr1_ext_phot_zero_point", "gaiadr1_cepheid", "gaiadr1_urat1_neighbourhood", "gaiadr1_urat1_best_neighbour", "gaiadr1_allwise_neighbourhood", "gaiadr1_variable_summary", "gaiadr1_tgas_source", "gaiadr1_tmass_best_neighbour", "gaiadr1_ucac4_original_valid", "gaiadr1_ppmxl_best_neighbour", "gaiadr1_phot_variable_time_series_gfov_statistical_parameters", "gaiadr1_sdssdr9_original_valid"]
gaiaedr3_gaia_source = []
gaiaedr3_allwise_best_neighbour = []
gaiaedr3_tycho2tdsc_merge_best_neighbour = []
gaiaedr3_urat1_neighbourhood = []
gaiaedr3_urat1_best_neighbour = []
gaiaedr3_gsc23_neighbourhood = []
gaiaedr3_tmass_psc_xsc_neighbourhood = []
gaiaedr3_panstarrs1_neighbourhood = []
gaiaedr3_skymapperdr2_best_neighbour = []
gaiaedr3_skymapperdr2_join = []
gaiaedr3_gaia_universe_model = []
gaiaedr3_gsc23_join = []
gaiaedr3_apassdr9_best_neighbour = []
gaiaedr3_frame_rotator_source = []
gaiaedr3_tycho2tdsc_merge_neighbourhood = []
gaiaedr3_tycho2tdsc_merge = []
gaiaedr3_sdssdr13_neighbourhood = []
gaiaedr3_ravedr5_join = []
gaiaedr3_ravedr5_neighbourhood = []
gaiaedr3_tmass_psc_xsc_join = []
gaiaedr3_sdssdr13_best_neighbour = []
gaiaedr3_dr2_neighbourhood = []
gaiaedr3_hipparcos2_neighbourhood = []
gaiaedr3_gaia_source_simulation = []
gaiaedr3_allwise_neighbourhood = []
gaiaedr3_apassdr9_join = []
gaiaedr3_gsc23_best_neighbour = []
gaiaedr3_apassdr9_neighbourhood = []
gaiaedr3_hipparcos2_best_neighbour = []
gaiaedr3_panstarrs1_best_neighbour = []
gaiaedr3_commanded_scan_law = []
gaiaedr3_tmass_psc_xsc_best_neighbour = []
gaiaedr3_agn_cross_id = []
gaiaedr3_ravedr5_best_neighbour = []
gaiaedr3_skymapperdr2_neighbourhood = []
gaiaedr3_panstarrs1_join = []
gaiaedr3_sdssdr13_join = []
gaiaedr3 = ["gaiaedr3_gaia_source", "gaiaedr3_allwise_best_neighbour", "gaiaedr3_tycho2tdsc_merge_best_neighbour", "gaiaedr3_urat1_neighbourhood", "gaiaedr3_urat1_best_neighbour", "gaiaedr3_gsc23_neighbourhood", "gaiaedr3_tmass_psc_xsc_neighbourhood", "gaiaedr3_panstarrs1_neighbourhood", "gaiaedr3_skymapperdr2_best_neighbour", "gaiaedr3_skymapperdr2_join", "gaiaedr3_gaia_universe_model", "gaiaedr3_gsc23_join", "gaiaedr3_apassdr9_best_neighbour", "gaiaedr3_frame_rotator_source", "gaiaedr3_tycho2tdsc_merge_neighbourhood", "gaiaedr3_tycho2tdsc_merge", "gaiaedr3_sdssdr13_neighbourhood", "gaiaedr3_ravedr5_join", "gaiaedr3_ravedr5_neighbourhood", "gaiaedr3_tmass_psc_xsc_join", "gaiaedr3_sdssdr13_best_neighbour", "gaiaedr3_dr2_neighbourhood", "gaiaedr3_hipparcos2_neighbourhood", "gaiaedr3_gaia_source_simulation", "gaiaedr3_allwise_neighbourhood", "gaiaedr3_apassdr9_join", "gaiaedr3_gsc23_best_neighbour", "gaiaedr3_apassdr9_neighbourhood", "gaiaedr3_hipparcos2_best_neighbour", "gaiaedr3_panstarrs1_best_neighbour", "gaiaedr3_commanded_scan_law", "gaiaedr3_tmass_psc_xsc_best_neighbour", "gaiaedr3_agn_cross_id", "gaiaedr3_ravedr5_best_neighbour", "gaiaedr3_skymapperdr2_neighbourhood", "gaiaedr3_panstarrs1_join", "gaiaedr3_sdssdr13_join"]
gaiadr3_apassdr9_join = []
gaiadr3_panstarrs1_join = []
gaiadr3_gold_sample_oba_stars = []
gaiadr3_frame_rotator_source = []
gaiadr3_alerts_mixedin_sourceids = []
gaiadr3_vari_rrlyrae = []
gaiadr3_galaxy_candidates = []
gaiadr3_gaia_crf3_xm = []
gaiadr3_skymapperdr2_neighbourhood = []
gaiadr3_astrophysical_parameters_supp = []
gaiadr3_vari_ms_oscillator = []
gaiadr3_hipparcos2_neighbourhood = []
gaiadr3_allwise_best_neighbour = []
gaiadr3_ravedr6_join = []
gaiadr3_astrophysical_parameters = []
gaiadr3_vari_spurious_signals = []
gaiadr3_urat1_best_neighbour = []
gaiadr3_commanded_scan_law = []
gaiadr3_sso_orbits = []
gaiadr3_qso_candidates = []
gaiadr3_vari_summary = []
gaiadr3_vari_microlensing = []
gaiadr3_panstarrs1_best_neighbour = []
gaiadr3_vari_classifier_class_definition = []
gaiadr3_gaia_source = []
gaiadr3_ravedr5_join = []
gaiadr3_sdssdr13_best_neighbour = []
gaiadr3_tmass_psc_xsc_neighbourhood = []
gaiadr3_galaxy_catalogue_name = []
gaiadr3_tycho2tdsc_merge_neighbourhood = []
gaiadr3_nss_acceleration_astro = []
gaiadr3_sso_source = []
gaiadr3_vari_long_period_variable = []
gaiadr3_vari_cepheid = []
gaiadr3_tmass_psc_xsc_join = []
gaiadr3_gold_sample_fgkm_stars = []
gaiadr3_sso_observation = []
gaiadr3_gsc23_join = []
gaiadr3_ravedr6_neighbourhood = []
gaiadr3_allwise_neighbourhood = []
gaiadr3_nss_non_linear_spectro = []
gaiadr3_vari_planetary_transit = []
gaiadr3_oa_neuron_information = []
gaiadr3_gold_sample_solar_analogues = []
gaiadr3_gsc23_best_neighbour = []
gaiadr3_vari_agn = []
gaiadr3_agn_cross_id = []
gaiadr3_tmass_psc_xsc_best_neighbour = []
gaiadr3_vari_classifier_result = []
gaiadr3_total_galactic_extinction_map = []
gaiadr3_urat1_neighbourhood = []
gaiadr3_gaia_source_lite = []
gaiadr3_gaia_universe_model = []
gaiadr3_tycho2tdsc_merge = []
gaiadr3_skymapperdr2_join = []
gaiadr3_dr2_neighbourhood = []
gaiadr3_vari_short_timescale = []
gaiadr3_apassdr9_neighbourhood = []
gaiadr3_oa_neuron_xp_spectra = []
gaiadr3_total_galactic_extinction_map_opt = []
gaiadr3_apassdr9_best_neighbour = []
gaiadr3_ravedr6_best_neighbour = []
gaiadr3_skymapperdr2_best_neighbour = []
gaiadr3_tycho2tdsc_merge_best_neighbour = []
gaiadr3_ravedr5_neighbourhood = []
gaiadr3_nss_vim_fl = []
gaiadr3_binary_masses = []
gaiadr3_panstarrs1_neighbourhood = []
gaiadr3_vari_epoch_radial_velocity = []
gaiadr3_science_alerts = []
gaiadr3_ravedr5_best_neighbour = []
gaiadr3_gold_sample_carbon_stars = []
gaiadr3_gold_sample_spss = []
gaiadr3_synthetic_photometry_gspc = []
gaiadr3_xp_summary = []
gaiadr3_gsc23_neighbourhood = []
gaiadr3_vari_rad_vel_statistics = []
gaiadr3_vari_compact_companion = []
gaiadr3_qso_catalogue_name = []
gaiadr3_nss_two_body_orbit = []
gaiadr3_chemical_cartography = []
gaiadr3_gold_sample_ucd = []
gaiadr3_sso_reflectance_spectrum = []
gaiadr3_vari_classifier_definition = []
gaiadr3_vari_rotation_modulation = []
gaiadr3_sdssdr13_join = []
gaiadr3_sdssdr13_neighbourhood = []
gaiadr3_vari_eclipsing_binary = []
gaiadr3_gaia_source_simulation = []
gaiadr3_hipparcos2_best_neighbour = []
gaiadr3_vari_planetary_transit_13june2022 = []
gaiadr3 = ["gaiadr3_apassdr9_join", "gaiadr3_panstarrs1_join", "gaiadr3_gold_sample_oba_stars", "gaiadr3_frame_rotator_source", "gaiadr3_alerts_mixedin_sourceids", "gaiadr3_vari_rrlyrae", "gaiadr3_galaxy_candidates", "gaiadr3_gaia_crf3_xm", "gaiadr3_skymapperdr2_neighbourhood", "gaiadr3_astrophysical_parameters_supp", "gaiadr3_vari_ms_oscillator", "gaiadr3_hipparcos2_neighbourhood", "gaiadr3_allwise_best_neighbour", "gaiadr3_ravedr6_join", "gaiadr3_astrophysical_parameters", "gaiadr3_vari_spurious_signals", "gaiadr3_urat1_best_neighbour", "gaiadr3_commanded_scan_law", "gaiadr3_sso_orbits", "gaiadr3_qso_candidates", "gaiadr3_vari_summary", "gaiadr3_vari_microlensing", "gaiadr3_panstarrs1_best_neighbour", "gaiadr3_vari_classifier_class_definition", "gaiadr3_gaia_source", "gaiadr3_ravedr5_join", "gaiadr3_sdssdr13_best_neighbour", "gaiadr3_tmass_psc_xsc_neighbourhood", "gaiadr3_galaxy_catalogue_name", "gaiadr3_tycho2tdsc_merge_neighbourhood", "gaiadr3_nss_acceleration_astro", "gaiadr3_sso_source", "gaiadr3_vari_long_period_variable", "gaiadr3_vari_cepheid", "gaiadr3_tmass_psc_xsc_join", "gaiadr3_gold_sample_fgkm_stars", "gaiadr3_sso_observation", "gaiadr3_gsc23_join", "gaiadr3_ravedr6_neighbourhood", "gaiadr3_allwise_neighbourhood", "gaiadr3_nss_non_linear_spectro", "gaiadr3_vari_planetary_transit", "gaiadr3_oa_neuron_information", "gaiadr3_gold_sample_solar_analogues", "gaiadr3_gsc23_best_neighbour", "gaiadr3_vari_agn", "gaiadr3_agn_cross_id", "gaiadr3_tmass_psc_xsc_best_neighbour", "gaiadr3_vari_classifier_result", "gaiadr3_total_galactic_extinction_map", "gaiadr3_urat1_neighbourhood", "gaiadr3_gaia_source_lite", "gaiadr3_gaia_universe_model", "gaiadr3_tycho2tdsc_merge", "gaiadr3_skymapperdr2_join", "gaiadr3_dr2_neighbourhood", "gaiadr3_vari_short_timescale", "gaiadr3_apassdr9_neighbourhood", "gaiadr3_oa_neuron_xp_spectra", "gaiadr3_total_galactic_extinction_map_opt", "gaiadr3_apassdr9_best_neighbour", "gaiadr3_ravedr6_best_neighbour", "gaiadr3_skymapperdr2_best_neighbour", "gaiadr3_tycho2tdsc_merge_best_neighbour", "gaiadr3_ravedr5_neighbourhood", "gaiadr3_nss_vim_fl", "gaiadr3_binary_masses", "gaiadr3_panstarrs1_neighbourhood", "gaiadr3_vari_epoch_radial_velocity", "gaiadr3_science_alerts", "gaiadr3_ravedr5_best_neighbour", "gaiadr3_gold_sample_carbon_stars", "gaiadr3_gold_sample_spss", "gaiadr3_synthetic_photometry_gspc", "gaiadr3_xp_summary", "gaiadr3_gsc23_neighbourhood", "gaiadr3_vari_rad_vel_statistics", "gaiadr3_vari_compact_companion", "gaiadr3_qso_catalogue_name", "gaiadr3_nss_two_body_orbit", "gaiadr3_chemical_cartography", "gaiadr3_gold_sample_ucd", "gaiadr3_sso_reflectance_spectrum", "gaiadr3_vari_classifier_definition", "gaiadr3_vari_rotation_modulation", "gaiadr3_sdssdr13_join", "gaiadr3_sdssdr13_neighbourhood", "gaiadr3_vari_eclipsing_binary", "gaiadr3_gaia_source_simulation", "gaiadr3_hipparcos2_best_neighbour", "gaiadr3_vari_planetary_transit_13june2022"]
tap_config_coord_sys = []
tap_config_properties = []
tap_config = ["tap_config_coord_sys", "tap_config_properties"]
external_gaiaedr3_gcns_main_1 = []
external_tmass_xsc = []
external_gaiadr2_astrophysical_parameters = []
external_skymapperdr1_master = []
external_gaiadr2_geometric_distance = []
external_galex_ais = []
external_ravedr5_gra = []
external_gaiaedr3_distance = []
external_ravedr5_dr5 = []
external_skymapperdr2_master = []
external_gaiaedr3_spurious = []
external_apassdr9 = []
external_catwise2020 = []
external_ravedr5_com = []
external_ravedr6 = []
external_sdssdr13_photoprimary = []
external_gaiaedr3_gcns_rejected_1 = []
external_gaia_eso_survey = []
external_ravedr5_on = []
external = ["external_gaiaedr3_gcns_main_1", "external_tmass_xsc", "external_gaiadr2_astrophysical_parameters", "external_skymapperdr1_master", "external_gaiadr2_geometric_distance", "external_galex_ais", "external_ravedr5_gra", "external_gaiaedr3_distance", "external_ravedr5_dr5", "external_skymapperdr2_master", "external_gaiaedr3_spurious", "external_apassdr9", "external_catwise2020", "external_ravedr5_com", "external_ravedr6", "external_sdssdr13_photoprimary", "external_gaiaedr3_gcns_rejected_1", "external_gaia_eso_survey", "external_ravedr5_on"]
gaiafpr_crowded_field_source = []
gaiafpr_lens_observation = []
gaiafpr_lens_candidates = []
gaiafpr_sso_source = []
gaiafpr_interstellar_medium_spectra = []
gaiafpr_lens_catalogue_name = []
gaiafpr_vari_long_period_variable = []
gaiafpr_lens_outlier = []
gaiafpr_vari_rad_vel_statistics = []
gaiafpr_vari_epoch_radial_velocity = []
gaiafpr_interstellar_medium_params = []
gaiafpr_sso_observation = []
gaiafpr = ["gaiafpr_crowded_field_source", "gaiafpr_lens_observation", "gaiafpr_lens_candidates", "gaiafpr_sso_source", "gaiafpr_interstellar_medium_spectra", "gaiafpr_lens_catalogue_name", "gaiafpr_vari_long_period_variable", "gaiafpr_lens_outlier", "gaiafpr_vari_rad_vel_statistics", "gaiafpr_vari_epoch_radial_velocity", "gaiafpr_interstellar_medium_params", "gaiafpr_sso_observation"]
job_upload = []
tap_upload = []
tap_schema_key_columns = []
tap_schema_tables = []
tap_schema_columns = []
tap_schema_keys = []
tap_schema_schemas = []
tap_schema = ["tap_schema_key_columns", "tap_schema_tables", "tap_schema_columns", "tap_schema_keys", "tap_schema_schemas"]
gaiadr2_ruwe = []
gaiadr2_panstarrs1_original_valid = []
gaiadr2_ppmxl_neighbourhood = []
gaiadr2_ravedr5_best_neighbour = []
gaiadr2_sdssdr9_best_neighbour = []
gaiadr2_tmass_neighbourhood = []
gaiadr2_sso_observation = []
gaiadr2_vari_classifier_definition = []
gaiadr2_vari_rrlyrae = []
gaiadr2_ravedr5_neighbourhood = []
gaiadr2_vari_short_timescale = []
gaiadr2_vari_long_period_variable = []
gaiadr2_urat1_best_neighbour = []
gaiadr2_gaia_source = []
gaiadr2_aux_allwise_agn_gdr2_cross_id = []
gaiadr2_vari_classifier_result = []
gaiadr2_sso_source = []
gaiadr2_tycho2_neighbourhood = []
gaiadr2_tmass_best_neighbour = []
gaiadr2_aux_sso_orbits = []
gaiadr2_hipparcos2_neighbourhood = []
gaiadr2_sdssdr9_neighbourhood = []
gaiadr2_vari_classifier_class_definition = []
gaiadr2_hipparcos2_best_neighbour = []
gaiadr2_allwise_neighbourhood = []
gaiadr2_aux_sso_orbit_residuals = []
gaiadr2_apassdr9_neighbourhood = []
gaiadr2_aux_iers_gdr2_cross_id = []
gaiadr2_allwise_best_neighbour = []
gaiadr2_gsc23_neighbourhood = []
gaiadr2_apassdr9_best_neighbour = []
gaiadr2_vari_time_series_statistics = []
gaiadr2_dr1_neighbourhood = []
gaiadr2_vari_rotation_modulation = []
gaiadr2_panstarrs1_best_neighbour = []
gaiadr2_panstarrs1_neighbourhood = []
gaiadr2_gsc23_best_neighbour = []
gaiadr2_ppmxl_best_neighbour = []
gaiadr2_vari_cepheid = []
gaiadr2_urat1_neighbourhood = []
gaiadr2_tycho2_best_neighbour = []
gaiadr2 = ["gaiadr2_ruwe", "gaiadr2_panstarrs1_original_valid", "gaiadr2_ppmxl_neighbourhood", "gaiadr2_ravedr5_best_neighbour", "gaiadr2_sdssdr9_best_neighbour", "gaiadr2_tmass_neighbourhood", "gaiadr2_sso_observation", "gaiadr2_vari_classifier_definition", "gaiadr2_vari_rrlyrae", "gaiadr2_ravedr5_neighbourhood", "gaiadr2_vari_short_timescale", "gaiadr2_vari_long_period_variable", "gaiadr2_urat1_best_neighbour", "gaiadr2_gaia_source", "gaiadr2_aux_allwise_agn_gdr2_cross_id", "gaiadr2_vari_classifier_result", "gaiadr2_sso_source", "gaiadr2_tycho2_neighbourhood", "gaiadr2_tmass_best_neighbour", "gaiadr2_aux_sso_orbits", "gaiadr2_hipparcos2_neighbourhood", "gaiadr2_sdssdr9_neighbourhood", "gaiadr2_vari_classifier_class_definition", "gaiadr2_hipparcos2_best_neighbour", "gaiadr2_allwise_neighbourhood", "gaiadr2_aux_sso_orbit_residuals", "gaiadr2_apassdr9_neighbourhood", "gaiadr2_aux_iers_gdr2_cross_id", "gaiadr2_allwise_best_neighbour", "gaiadr2_gsc23_neighbourhood", "gaiadr2_apassdr9_best_neighbour", "gaiadr2_vari_time_series_statistics", "gaiadr2_dr1_neighbourhood", "gaiadr2_vari_rotation_modulation", "gaiadr2_panstarrs1_best_neighbour", "gaiadr2_panstarrs1_neighbourhood", "gaiadr2_gsc23_best_neighbour", "gaiadr2_ppmxl_best_neighbour", "gaiadr2_vari_cepheid", "gaiadr2_urat1_neighbourhood", "gaiadr2_tycho2_best_neighbour"]
